### ISSUE TITLE
Website needs responsive design!

### ISSUE THREAD

**Issue by LBeul** [LBeul/website_networks#1]
By now, the whole site is optimized for a pc monitor or laptop. 
To make it responsive and prettier on mobile phones or tablets, one has to add some media queries and play a bit with flexbox and grid. We're just using _normalizeCSS_ to delete the standardized margins & decoration properties that some browsers apply automatically and used _SkeletonCSS_ for basic properties like container margins and default table styles.

**Feel free to modify the CSS to make the site responsive!**

**Comment by liloo2040** [comment]
Hello! I would like to help you on this issue.
